export const EPSILON = 0.001
export const MOVABLE_BOUNDING_RADIUS = 0.4
export const TILE_SIZE_IN_COORDS = 1
export const HALF_TILE_SIZE_IN_COORDS = TILE_SIZE_IN_COORDS / 2
export const GLOBAL_SPEED_FACTOR = 0.02
